### ISSUE TITLE
VirtualBox don't work with akmod!

### ISSUE THREAD

**Issue by cmirnow** [Hubbitus/kernel#2]
Help please. My virtual machine don't work after update kernel..... I can ask kmod-virtualbox\* ?
# systemctl status systemd-modules-load.service

● systemd-modules-load.service - Load Kernel Modules
   Loaded: loaded (/usr/lib/systemd/system/systemd-modules-load.service; static)
   Active: failed (Result: exit-code) since Пт 2015-03-20 14:22:20 MSK; 9min ago
     Docs: man:systemd-modules-load.service(8)
           man:modules-load.d(5)
  Process: 9150 ExecStart=/usr/lib/systemd/systemd-modules-load (code=exited, status=1/FAILURE)
 Main PID: 9150 (code=exited, status=1/FAILURE)

мар 20 14:22:20 localhost.localdomain systemd-modules-load[9150]: Failed to find module 'vboxdrv'
мар 20 14:22:20 localhost.localdomain systemd[1]: systemd-modules-load.service: main process ex...RE
мар 20 14:22:20 localhost.localdomain systemd[1]: Failed to start Load Kernel Modules.
мар 20 14:22:20 localhost.localdomain systemd[1]: Unit systemd-modules-load.service entered fai...e.
мар 20 14:22:20 localhost.localdomain systemd[1]: systemd-modules-load.service failed.
Hint: Some lines were ellipsized, use -l to show in full.

**Comment by Hubbitus** [comment]
Attach full logs and show what packages you are using.

**Comment by cmirnow** [comment]
[aleksej@localhost ~]$ yum info VirtualBox
Загружены модули: langpacks, remove-with-leaves
google-chrome/primary                                                           | 1.9 kB  00:00:00  
google-chrome                                                                                      3/3
Установленные пакеты
Название: VirtualBox
Архитектура: i686
Версия: 4.3.20
Выпуск: 3.fc21
Объем: 59 M
Источник: installed
Из источника: rpmfusion-free-updates
Аннотация: A general-purpose full virtualizer for PC hardware
Ссылка: http://www.virtualbox.org/wiki/VirtualBox
Лицензия: GPLv2 or (GPLv2 and CDDL)
Описание: A general-purpose full virtualizer and emulator for 32-bit and
        : 64-bit x86 based PC-compatible machines.

[aleksej@localhost ~]$ sudo systemctl status systemd-modules-load.service
[sudo] пароль для aleksej: 
● systemd-modules-load.service - Load Kernel Modules
   Loaded: loaded (/usr/lib/systemd/system/systemd-modules-load.service; static)
   Active: failed (Result: exit-code) since Пт 2015-03-20 15:10:47 MSK; 37min ago
     Docs: man:systemd-modules-load.service(8)
           man:modules-load.d(5)
  Process: 484 ExecStart=/usr/lib/systemd/systemd-modules-load (code=exited, status=1/FAILURE)
 Main PID: 484 (code=exited, status=1/FAILURE)

мар 20 15:10:47 localhost.localdomain systemd-modules-load[484]: Failed to find module 'vboxdrv'
мар 20 15:10:47 localhost.localdomain systemd[1]: systemd-modules-load.service: main process ex...RE
мар 20 15:10:47 localhost.localdomain systemd[1]: Failed to start Load Kernel Modules.
мар 20 15:10:47 localhost.localdomain systemd[1]: Unit systemd-modules-load.service entered fai...e.
мар 20 15:10:47 localhost.localdomain systemd[1]: systemd-modules-load.service failed.
Hint: Some lines were ellipsized, use -l to show in full.
[aleksej@localhost ~]$ sudo journalctl -xe  
мар 20 15:11:33 localhost.localdomain kernel: Request for unknown module key 'Fedora kernel signing key
мар 20 15:11:33 localhost.localdomain kernel: Bluetooth: BNEP (Ethernet Emulation) ver 1.3
мар 20 15:11:33 localhost.localdomain kernel: Bluetooth: BNEP filters: protocol multicast
мар 20 15:11:33 localhost.localdomain kernel: Bluetooth: BNEP socket layer initialized
мар 20 15:11:33 localhost.localdomain dbus[673]: [system] Activating via systemd: service name='org.fre
мар 20 15:11:33 localhost.localdomain bluetoothd[1402]: Bluetooth management interface 1.8 initialized
мар 20 15:11:33 localhost.localdomain NetworkManager[802]: <info>  use BlueZ version 5
мар 20 15:11:33 localhost.localdomain kernel: SELinux: initialized (dev tmpfs, type tmpfs), uses transi
мар 20 15:11:33 localhost.localdomain dbus[673]: [system] Successfully activated service 'org.freedeskt
мар 20 15:11:34 localhost.localdomain org.freedesktop.Telepathy.AccountManager[1231]: GLib-GIO-Message:
мар 20 15:11:37 localhost.localdomain NetworkManager[802]: <info>  Activation (enp1s0) Stage 4 of 5 (IP
мар 20 15:11:37 localhost.localdomain NetworkManager[802]: <info>  Activation (enp1s0) Stage 4 of 5 (IP
мар 20 15:11:37 localhost.localdomain NetworkManager[802]: <info>  Activation (enp1s0) Stage 4 of 5 (IP
мар 20 15:11:38 localhost.localdomain vmusr[1526]: [ warning] [vmtoolsd] The vmusr service needs to run
мар 20 15:11:39 localhost.localdomain rtkit-daemon[649]: Successfully made thread 1541 of process 1541 
мар 20 15:11:39 localhost.localdomain rtkit-daemon[649]: Supervising 1 threads of 1 processes of 1 user
мар 20 15:11:49 localhost.localdomain polkitd[738]: Registered Authentication Agent for unix-session:1 
мар 20 15:11:51 localhost.localdomain org.a11y.Bus[1231]: GLib-GIO-Message: Using the 'memory' GSetting
мар 20 15:11:51 localhost.localdomain org.a11y.Bus[1231]: Activating service name='org.a11y.atspi.Regis
мар 20 15:11:51 localhost.localdomain org.a11y.Bus[1231]: Successfully activated service 'org.a11y.atsp
мар 20 15:11:51 localhost.localdomain org.a11y.atspi.Registry[1702]: SpiRegistry daemon is running with
мар 20 15:11:51 localhost.localdomain org.a11y.atspi.Registry[1702]: Xlib:  extension "XEVIE" missing o
мар 20 15:19:14 localhost.localdomain kernel: SELinux: initialized (dev proc, type proc), uses genfs_co
мар 20 15:20:26 localhost.localdomain kernel: perf interrupt took too long (2501 > 2500), lowering kern
мар 20 15:20:51 localhost.localdomain dnf[3697]: cachedir: /var/cache/dnf/i386/21/i386/21
мар 20 15:20:52 localhost.localdomain dnf[3697]: DNF version: 0.6.4
мар 20 15:20:52 localhost.localdomain dnf[3697]: Создание кэша для всех метаданных файлов.
мар 20 15:20:52 localhost.localdomain dnf[3697]: Metadata cache refreshed recently.
мар 20 15:22:26 localhost.localdomain kernel: SELinux: initialized (dev proc, type proc), uses genfs_co
мар 20 15:41:49 localhost.localdomain kernel: perf interrupt took too long (5009 > 5000), lowering kern
мар 20 15:48:41 localhost.localdomain dbus[673]: [system] Activating via systemd: service name='net.rea
мар 20 15:48:41 localhost.localdomain dbus[673]: [system] Successfully activated service 'net.reactivat
мар 20 15:48:44 localhost.localdomain sudo[9238]: aleksej : TTY=pts/2 ; PWD=/home/aleksej ; USER=root ;
мар 20 15:48:44 localhost.localdomain sudo[9238]: pam_unix(sudo:session): session opened for user root 
мар 20 15:48:45 localhost.localdomain sudo[9238]: pam_unix(sudo:session): session closed for user root
мар 20 15:48:53 localhost.localdomain sudo[9281]: aleksej : TTY=pts/2 ; PWD=/home/aleksej ; USER=root ;
мар 20 15:48:53 localhost.localdomain sudo[9281]: pam_unix(sudo:session): session opened for user root 
lines 1169-1205/1205 (END)

**Comment by Hubbitus** [comment]
I do not see there anything related to VirtualBox module.

**Comment by cmirnow** [comment]
http://pix.academ.org/img/2015/03/22/82f45480c1f32783eb63e5cace9bf32e.jpg

Не удалось открыть сессию для виртуальной машины XP.

The virtual machine 'XP' has terminated unexpectedly during startup with exit code 1 (0x1).

Код ошибки: NS_ERROR_FAILURE (0x80004005)
Компонент: Machine
Интерфейс: IMachine {480cf695-2d8d-4256-9c7c-cce4184fa048}

**Comment by Hubbitus** [comment]
It is not my kernel problem. It is incompatibility of current VirtualBox modules with new kernel:
http://forums.fedoraforum.org/showthread.php?t=303666

Also, it break several things: https://communities.vmware.com/message/2469395, https://github.com/zfsonlinux/zfs/issues/2959.

Last link describe changes and contain information how to make patch.

So, this bug should be forwarded to VirtualBox module maintainers. So, please fill it in RPMFusion bugzilla.

I personally do not use VirtualBox and do not willing maintain its modules. In the past when I had use them it always was painful with recent kernels. So I may advise you switch to in kernel KVM (virt-manager) it have no such problems, faster and native.
