### ISSUE TITLE
kernel BUG at mm/uksm.c:4155!

### ISSUE THREAD

**Issue by xes** [Hubbitus/kernel#3]
I'm testing your kernel in a few different laptops (Lenovo/Dell/Acer) but all them freeze after some hour of work. 
Hardware is very different: cpu centrino/core 2 duo/i5 and the video card is integrated intel video card or nvidia, but the result is always the same. 
Graphical desktop is completely freezed but the pc is reachable by ssh.

Here attached the syslog trace:

[ 2591.847570] ------------[ cut here ]------------
[ 2591.847609] kernel BUG at mm/uksm.c:4155!
[ 2591.847626] invalid opcode: 0000 [#1] SMP
[ 2591.847646] Modules linked in: option usb_wwan qmi_wwan cdc_wdm cdc_ether usbnet mii uas usb_storage rfcomm ccm fuse zram lz4_compress bfq_iosched bnep btusb btrtl btbcm btintel bluetooth iTCO_wdt iTCO_vendor_support ppdev snd_hda_codec_analog snd_hda_codec_generic wl(POE) coretemp snd_hda_intel kvm joydev snd_hda_codec snd_hda_core snd_hwdep snd_seq i2c_i801 snd_seq_device r592 memstick snd_pcm arc4 lpc_ich snd_timer iwl4965 iwlegacy thinkpad_acpi mac80211 snd cfg80211 soundcore rfkill parport_pc parport shpchp tpm_tis tpm acpi_cpufreq binfmt_misc dm_multipath nouveau mxm_wmi i2c_algo_bit drm_kms_helper ttm sdhci_pci sdhci e1000e drm serio_raw ata_generic pata_acpi firewire_ohci firewire_core mmc_core yenta_socket crc_itu_t ptp pps_core wmi video
[ 2591.848084] CPU: 0 PID: 96 Comm: uksmd Tainted: P           OE   4.2.3-200.hu.1.pf2.fc22.x86_64 #1
[ 2591.848103] Hardware name: LENOVO 89185WG/89185WG, BIOS 7KETB0WW (2.10 ) 01/21/2008
[ 2591.848118] task: ffff880079bc3500 ti: ffff880036aa0000 task.ti: ffff880036aa0000
[ 2591.848118] RIP: 0010:[<ffffffff811efc0f>]  [<ffffffff811efc0f>] uksm_del_vma_slot+0x48f/0x610
[ 2591.848118] RSP: 0018:ffff880036aa3ce8  EFLAGS: 00010286
[ 2591.848118] RAX: 00000000ffffffff RBX: ffff88000d7a6000 RCX: 0000000180330030
[ 2591.848118] RDX: 0000000000000000 RSI: ffffea0000bde780 RDI: 0000000040000000
[ 2591.848118] RBP: ffff880036aa3d48 R08: 000000002f79ec01 R09: 0000000180330030
[ 2591.848118] R10: ffff88002f79ec80 R11: 0000000000019798 R12: 0000000000000000
[ 2591.848118] R13: ffff88002f761fc0 R14: ffff88000d7a6000 R15: ffff88005c803228
[ 2591.848118] FS:  0000000000000000(0000) GS:ffff88007fc00000(0000) knlGS:0000000000000000
[ 2591.848118] CS:  0010 DS: 0000 ES: 0000 CR0: 000000008005003b
[ 2591.848118] CR2: 00007f152a444140 CR3: 0000000001c0b000 CR4: 00000000000006f0
[ 2591.848118] Stack:
[ 2591.848118]  ffff880036aa3d38 0000000000000000 0000000000000296 ffff88007fc16740
[ 2591.848118]  ffff880000000000 0000000000000000 ffff880067fbd5c0 ffffffff82030400
[ 2591.848118]  ffffffff82030378 0000000000000020 ffffffff820305c0 0000000000000005
[ 2591.848118] Call Trace:
[ 2591.848118]  [<ffffffff811f4dca>] uksm_do_scan+0xf0a/0x2cd0
[ 2591.848118]  [<ffffffff810fc5dc>] ? del_timer_sync+0x4c/0x60
[ 2591.848118]  [<ffffffff8176d269>] ? schedule_timeout+0x129/0x240
[ 2591.848118]  [<ffffffff811f6cec>] uksm_scan_thread+0x15c/0x1a0
[ 2591.848118]  [<ffffffff811f6b90>] ? uksm_do_scan+0x2cd0/0x2cd0
[ 2591.848118]  [<ffffffff811f6b90>] ? uksm_do_scan+0x2cd0/0x2cd0
[ 2591.848118]  [<ffffffff810ba0c8>] kthread+0xd8/0xf0
[ 2591.848118]  [<ffffffff810b9ff0>] ? kthread_worker_fn+0x160/0x160
[ 2591.848118]  [<ffffffff8176e91f>] ret_from_fork+0x3f/0x70
[ 2591.848118]  [<ffffffff810b9ff0>] ? kthread_worker_fn+0x160/0x160
[ 2591.848118] Code: 88 ae 1a 00 4d 8b 6c 24 40 49 8d 7d 30 e8 0a 27 1c 00 48 8b 3d a3 0d e4 00 4c 89 ee e8 db b7 00 00 49 8b 44 24 10 e9 52 fd ff ff <0f> 0b 48 c7 83 d8 00 00 00 01 00 00 00 e9 49 fc ff ff 49 8b 87
[ 2591.848118] RIP  [<ffffffff811efc0f>] uksm_del_vma_slot+0x48f/0x610
[ 2591.848118]  RSP <ffff880036aa3ce8>
[ 2591.856453] ---[ end trace 4397d202ff134912 ]---

**Comment by Hubbitus** [comment]
Hello @xes.
First very thank you for the bugreport.
It is very strange, because I use my kernel all the time (sometimes pf). Could you please provide exact version what you try?

**Comment by xes** [comment]
Hi @Hubbitus!
I'm using Fedora 22 x86_64 with your  4.2.3-200.hu.1.pf2.fc22.x86_64. What do you mean with "exact version"?
I can confirm that is strange since i'm using the same kernel with a Dell desktop pc, a Lenovo T410 and all is working perfectly... 
With the R61 of previous trace, a Dell latitude 3450, and a Toshiba portege is a complete NO-GO.
In about 2 hours of work you obtain the error and the desktop is completely freezed.

**Comment by Hubbitus** [comment]
Could you please test if previous my kernel http://rpm.hubbitus.info/Fedora22/kernel-hubbitus/ works for you?

**Comment by xes** [comment]
Thank you but i'm not interested into go back to 4.1.x since there are too many issues with nouveau drivers. 
Anyway, after a few hours of work i can see the same freeze also with the Lenovo T410 that i was thinking stable so far.

**Comment by Hubbitus** [comment]
Ok, ok.
How about http://rpm.hubbitus.info/Fedora23/kernel-pf/ ?

**Comment by xes** [comment]
Many thanks, i will try it for a few days.

**Comment by Hubbitus** [comment]
I close it now as it works for me and no feedback after 12 days. But please write if it sis not fixed for you.
